import { useState } from 'react';
import { Link, useLocation } from 'react-router-dom';
import { Settings2 } from 'lucide-react';
import { BrandMark } from './BrandMark.jsx';
import { fmtMoney, fmtPct, fmtNum } from '../dash/charts/theme.js';
import { salesPaceStatus, paceStatus, share } from '../adsOverview.js';
import './adsWorkspace.css';
import { WorkspaceTrends } from './WorkspaceTrends.jsx';
import { AdsControlCenter } from './AdsControlCenter.jsx';
import { GoalLine } from '../ui/GoalLine.jsx';
import { AdsSourceControl, AdsSourceNotice } from './AdsSourceControl.jsx';

const money = n => n == null ? '—' : fmtMoney(n);
const pct = n => n == null ? '—' : fmtPct(n, 1);
function Track({ value, expected, label, tone }) {
  return <div className="aw-track" role="img" aria-label={`${label}: ${pct(value)} · จังหวะวันนี้ ${pct(expected)}`}><i className={tone} style={{width:`${Math.max(0,Math.min(100,(value ?? 0)*100))}%`}} />{expected != null && <em style={{left:`${Math.min(100,expected*100)}%`}} />}</div>;
}
export function AdsWorkspace({ v, ads, controls, ChannelCard, SalePipeline, settings, updateAdsControl, toast }) {
  const { search } = useLocation();
  const [selected, setSelected] = useState(null);
  const [tab, setTab] = useState('platform');
  const picked = v.brands.find(x=>x.id===selected);
  const overview = !picked;
  const s = v.summary;
  const b = picked ?? (v.brands.length ? {...s, id:'overview',name:'ภาพรวมทุกแบรนด์',pctAds:s.pctAds !== undefined ? s.pctAds : share(s.spend,s.revenue),channels:[],revPace:{...s.revPace,expectedToDate:s.revPace.expectedSpend,pctOfExpected:s.revPctOfExpected,forecastVsTarget:s.revPace.forecastOver,behind:s.revPace.vsPace==null?null:-s.revPace.vsPace}} : null);
  const pipeline = overview ? v.overallPipeline : v.pipelines[b.id];
  const goals = overview ? v.goals?.overall : v.goals?.byBrand?.[b?.id];
  /* mv = โหมด "เดือนนี้" (มีเป้า/จังหวะ/คาดการณ์) · ไม่ใช่ = โหมดช่วงที่เลือก: ยอดของช่วงล้วน เทียบช่วงก่อน */
  const mv = v.monthView;
  const chg = (n) => n == null ? { tone: 'zinc', text: `เทียบ${v.compareLabel}ไม่ได้` } : { tone: n >= 0 ? 'emerald' : 'rose', text: `${n >= 0 ? '+' : ''}${fmtNum(n, 2)}% เทียบ${v.compareLabel}` };
  const rst = b ? (mv ? salesPaceStatus(b.revPace.pctOfExpected) : chg(b.revChangePct)) : null;
  const bst = b ? paceStatus(b.pace) : null;
  const roas = pipeline?.items.find(x=>x.key==='roas')?.value;
  const revenueLabel = v.revenueBasis === 'new' ? 'ยอดใหม่' : 'ยอดรวม';
  /* ข้อมูลจริง: ยอด เป้า งบ มาจากระบบขาย — บอกให้ชัดเวลาที่ยังไม่มี (แผน 2026-09-17: ยังไม่มีข้อมูล · ยังไม่ตั้งเป้า · รอเชื่อมแหล่งข้อมูล) */
  const real = ads.source === "meta_pilot";
  const noSales = (row) => row?.salesSource === 'waiting' ? 'รอเชื่อมแหล่งข้อมูล' : row?.salesSource === 'none' ? 'ยังไม่มีข้อมูลยอดขาย' : null;
  const targetText = (value) => value == null ? (real ? 'ยังไม่ตั้งเป้า' : '—') : money(value);
  if (new URLSearchParams(search).get('panel') === 'settings') {
    return <AdsControlCenter brands={v.brands} saved={settings?.ads_control} onSave={updateAdsControl} toast={toast}/>;
  }
  return <main className="aw">
    <section className="aw-toolbar" aria-label="ตัวกรองรายงาน"><header className="aw-header"><div><h1>Overview ads</h1><p>ยอดขาย งบ และประสิทธิภาพรวมทุกแบรนด์</p></div><div className="aw-header-actions"><AdsSourceControl ads={ads}/><Link className="aw-settings-link" to="/mkt/ads?panel=settings"><Settings2 size={15}/> ตั้งค่า</Link></div></header><AdsSourceNotice ads={ads}/><div className="aw-controls">{controls}</div></section>
    <div className="aw-layout">
      <aside className="aw-brands"><div className="aw-section-label">พอร์ตแบรนด์ <span>{v.brands.length}</span></div><p>{mv ? `${revenueLabel}และเป้ารวมเดือนปัจจุบัน` : `${revenueLabel} · ${v.rangeLabel}`}</p>{<button type="button" className={`aw-brand ${overview?'selected':''}`} aria-pressed={overview} onClick={()=>setSelected(null)}><div><strong>ภาพรวมทุกแบรนด์</strong><span>↗</span></div><b>{money(s.revenue)}</b><small> {mv ? `${revenueLabel}เดือนปัจจุบัน` : v.rangeLabel}</small></button>}{v.brands.map(x=>{const st=mv?salesPaceStatus(x.revPace.pctOfExpected):chg(x.revChangePct);return <button key={x.id} type="button" className={`aw-brand ${x.id===b?.id?'selected':''}`} onClick={()=>setSelected(x.id)} aria-pressed={x.id===b?.id}><div><BrandMark brand={x}/><strong>{x.name}</strong><span>↗</span></div><div><b>{money(x.revenue)}</b><small>{mv ? `${pct(x.revPct)} ของเป้ารวม` : `${pct(x.revShare)} ของยอดรวม`}</small></div>{mv ? <Track value={x.revPct} expected={x.pace.expected} label={x.name} tone={st.tone}/> : <Track value={x.revShare} label={x.name} tone="zinc"/>}<small className={noSales(x) ? 'zinc' : st.tone}>{noSales(x) ?? st.text}</small></button>})}<div className="aw-key">{mv ? 'ขีดบนแถบ = จังหวะที่ควรถึงวันนี้' : 'แถบ = สัดส่วนของยอดรวมในช่วงที่เลือก'}</div></aside>
      {b ? <div className="aw-content">
        <section className="aw-hero"><div className="aw-hero-top"><div className="aw-brand-title">{!overview&&<BrandMark brand={b}/>}<h2>{b.name}</h2></div><span className={`aw-status ${rst.tone}`}>{rst.text}</span></div>
          {mv ? <div className="aw-hero-grid"><div><span className="aw-eyebrow">{revenueLabel}เดือนปัจจุบัน{real ? " · จากระบบขาย" : ""}</span><div className="aw-revenue">{money(b.revenue)}</div><p>{noSales(b) ? <b>{noSales(b)}</b> : <>{revenueLabel === 'ยอดใหม่' ? 'จากเป้ารวม' : 'จากเป้า'} <b>{targetText(b.revTarget)}</b>{b.revTarget != null && <span> · ทำได้ {pct(b.revPct)}</span>}</>}</p>{overview && real && s.excludedWaiting?.length > 0 && <p className="aw-key">ไม่รวม {s.excludedWaiting.join(' · ')} (รอเชื่อมแหล่งข้อมูลยอดขาย)</p>}{overview && real && s.excludedNoData?.length > 0 && <p className="aw-key">ไม่รวม {s.excludedNoData.join(' · ')} (ช่วงนี้ยังไม่มีข้อมูลยอดขาย)</p>}<Track value={b.revPct} expected={b.pace.expected} tone={rst.tone} label="ยอดขายเทียบเป้า"/><div className="aw-hero-foot"><span>ควรได้วันนี้ {money(b.revPace.expectedToDate)}</span><span>{b.revChangePct==null?'เทียบเดือนก่อนไม่ได้':`${b.revChangePct>=0?'+':''}${fmtNum(b.revChangePct, 2)}% เทียบเดือนก่อน`}</span></div></div>
          <div className="aw-forecast"><span>หากรักษาจังหวะปัจจุบัน</span><h3>{money(b.revPace.forecast)}</h3><p>คาดการณ์ยอดขายสิ้นเดือน</p><strong className={b.revPace.forecastVsTarget<0?'rose':'emerald'}>{b.revPace.forecastVsTarget==null?'ยังประเมินเทียบเป้าไม่ได้':`${b.revPace.forecastVsTarget<0?'ต่ำกว่าเป้า':'เหนือเป้า'} ${money(Math.abs(b.revPace.forecastVsTarget))}`}</strong><small>คาดการณ์จากค่าเฉลี่ยสะสม ไม่รวมการเปลี่ยนแผนในอนาคต</small></div></div>
          : <div className="aw-hero-grid"><div><span className="aw-eyebrow">{revenueLabel} · {v.rangeLabel}{real ? " · จากระบบขาย" : ""}</span><div className="aw-revenue">{money(b.revenue)}</div><p>{v.compareLabel} <b>{money(b.prevRevenue)}</b> <span>· {rst.text}</span></p><div className="aw-hero-foot"><span>ค่าแอด {money(b.spend)} · %Ads {pct(b.pctAds)}</span><span>เป้า/จังหวะรายเดือนดูได้เมื่อเลือก "เดือนนี้"</span></div></div>
          <div className="aw-forecast"><span>ค่าแอดในช่วงนี้</span><h3>{money(b.spend)}</h3><p>{v.compareLabel} {money(b.prevSpend)}</p><strong className={b.spendChangePct==null?'zinc':b.spendChangePct>0?'rose':'emerald'}>{b.spendChangePct==null?'เทียบไม่ได้':`${b.spendChangePct>=0?'+':''}${fmtNum(b.spendChangePct, 2)}% ${b.spendChangePct>0?'ใช้มากขึ้น':'ใช้น้อยลง'}`}</strong><small>ROAS ช่วงนี้ {roas==null?'—':`${fmtNum(roas, 2)}×`}</small></div></div>}
        </section>
        <div className="aw-middle">{mv ? <section className="aw-panel"><div className="aw-section-label">{real ? 'งบโฆษณา Meta' : 'งบโฆษณา'} <span className={b.budget == null && real ? 'zinc' : bst.tone}>{b.budget == null && real ? 'ยังไม่ตั้งเป้างบ' : bst.text}</span></div><div className="aw-spend">{money(b.spend)} <small>/ {targetText(b.budget)}</small></div><Track value={b.pace.used} expected={b.pace.expected} tone={bst.tone} label="ใช้เงินเทียบงบ"/><dl className="aw-facts"><div><dt>งบคงเหลือ</dt><dd>{money(b.pace.remaining)}</dd></div><div><dt>เฉลี่ยต่อวัน</dt><dd>{money(b.pace.average)}</dd></div><div><dt>คาดใช้สิ้นเดือน</dt><dd>{money(b.pace.forecast)}</dd></div><div><dt>เหลือเวลา</dt><dd>{b.pace.daysLeft} วัน</dd></div></dl></section>
        : <section className="aw-panel"><div className="aw-section-label">ค่าแอด <span className="zinc">{v.rangeLabel}</span></div><div className="aw-spend">{money(b.spend)}</div><Track value={b.spendShare ?? (overview ? 1 : null)} label="สัดส่วนค่าแอด" tone="zinc"/><dl className="aw-facts"><div><dt>{v.compareLabel}</dt><dd>{money(b.prevSpend)}</dd></div><div><dt>เปลี่ยนแปลง</dt><dd>{b.spendChangePct==null?'—':`${b.spendChangePct>=0?'+':''}${fmtNum(b.spendChangePct, 2)}%`}</dd></div><div><dt>ลีด</dt><dd>{b.leads==null?'—':b.leads.toLocaleString('th-TH')}</dd></div><div><dt>CPL</dt><dd>{money(share(b.spend,b.leads))}</dd></div></dl></section>}
        <section className="aw-panel aw-efficiency"><div className="aw-section-label">ประสิทธิภาพ{real && <span className="zinc">คิดจากค่าแอด Meta</span>}</div><div><span>ROAS <small>ช่วงที่เลือก</small></span><b>{roas==null?'—':`${fmtNum(roas, 2)}×`}</b>{roas==null && noSales(b) ? <small className="aw-key">{noSales(b)}</small> : <GoalLine metric="roas" goal={goals?.roas}/>}</div><div><span>%Ads <small>{real ? 'ต่อยอดลูกค้าใหม่' : mv?'เดือนปัจจุบัน':'ช่วงที่เลือก'}</small></span><b>{pct(b.pctAds)}</b>{b.pctAds==null && noSales(b) ? <small className="aw-key">{noSales(b)}</small> : <GoalLine metric="pctAds" goal={goals?.pctAds}/>}</div><p>{real ? <>ROAS = ยอดขายจริง ÷ ค่าแอด Meta<br/>%Ads = ค่าแอด Meta ÷ ยอดลูกค้าใหม่</> : <>ROAS = ยอดขาย ÷ ค่าแอด<br/>%Ads = ค่าแอด ÷ ยอดขาย</>}</p></section></div>
        {overview && (mv ? <section className="aw-panel"><div className="aw-section-label">เปรียบเทียบแบรนด์ <span>{revenueLabel}และงบเดือนปัจจุบัน · ROAS ช่วงที่เลือก</span></div><div className="aw-table-scroll"><table className="aw-comparison"><thead><tr><th>แบรนด์</th><th>{revenueLabel} / เป้ารวม</th><th>จังหวะ{revenueLabel}</th><th>จังหวะงบ</th><th>ROAS</th><th>สถานะยอดขาย</th></tr></thead><tbody>{v.brands.map(x=>{const st=salesPaceStatus(x.revPace.pctOfExpected);const r=v.pipelines[x.id]?.items.find(i=>i.key==='roas')?.value;return <tr key={x.id}><th><button onClick={()=>setSelected(x.id)}>{x.name} ↗</button></th><td>{money(x.revenue)}<small> / {money(x.revTarget)}</small></td><td><Track value={x.revPct} expected={x.pace.expected} label={revenueLabel} tone={st.tone}/>{pct(x.revPct)}</td><td><Track value={x.pace.used} expected={x.pace.expected} label="งบ" tone={paceStatus(x.pace).tone}/>{pct(x.pace.used)}</td><td>{r==null?'—':`${fmtNum(r, 2)}×`}</td><td className={st.tone}>{st.text}</td></tr>})}</tbody></table></div></section>
        : <section className="aw-panel"><div className="aw-section-label">เปรียบเทียบแบรนด์ <span>{revenueLabel}และค่าแอด · {v.rangeLabel}</span></div><div className="aw-table-scroll"><table className="aw-comparison"><thead><tr><th>แบรนด์</th><th>{revenueLabel}</th><th>สัดส่วน{revenueLabel}</th><th>ค่าแอด</th><th>ROAS</th><th>{v.compareLabel}</th></tr></thead><tbody>{v.brands.map(x=>{const st=chg(x.revChangePct);const r=v.pipelines[x.id]?.items.find(i=>i.key==='roas')?.value;return <tr key={x.id}><th><button onClick={()=>setSelected(x.id)}>{x.name} ↗</button></th><td>{money(x.revenue)}</td><td><Track value={x.revShare} label={revenueLabel} tone="zinc"/>{pct(x.revShare)}</td><td>{money(x.spend)}<small> · %Ads {pct(x.pctAds)}</small></td><td>{r==null?'—':`${fmtNum(r, 2)}×`}</td><td className={st.tone}>{st.text}</td></tr>})}</tbody></table></div></section>)}
        <WorkspaceTrends v={v} brandId={overview?null:b.id} sales={real ? ads.sales : null}/>
        <section className="aw-panel aw-journey"><div className="aw-section-label">จากความสนใจ สู่ยอดขาย <span>ช่วงที่เลือก</span></div><SalePipeline row items={(pipeline?.items??[]).slice(0,4)} worstKey={pipeline?.worstKey} goals={goals}/>{real ? <p className="aw-key">ตัวเลขจากระบบขาย · คนทัก = ที่ทีมขายกรอก (จากแอด Meta แสดงใต้ตัวเลข) · ได้ออเดอร์ = เข้าสเตจออกแบบครั้งแรก · ยืนยันออเดอร์ = รับรู้ยอด</p> : pipeline?.estimated&&<p className="aw-key">Meta บอกได้แค่ “คนทัก” — Lead มัดจำ และออเดอร์จะขึ้นเมื่อเชื่อมระบบขายแล้ว (ตอนนี้ขึ้น “—” แทนการประมาณ)</p>}</section>
        {!overview && <section className="aw-panel aw-detail"><div className="aw-tabs" role="tablist" aria-label="รายละเอียดแบรนด์"><button role="tab" aria-selected={tab==='platform'} onClick={()=>setTab('platform')}>แพลตฟอร์ม <span>{b.channels.length}</span></button>{mv && <button role="tab" aria-selected={tab==='plan'} onClick={()=>setTab('plan')}>รายละเอียดแผน</button>}</div>{(tab==='platform'||!mv)?<div className="aw-channel-grid">{b.channels.length?b.channels.map(c=><ChannelCard key={c.key} c={c} monthView={mv}/>):<p>ไม่มีแพลตฟอร์มในตัวกรองนี้</p>}</div>:<dl className="aw-facts aw-plan"><div><dt>ยอดขายที่ยังขาดจากจังหวะวันนี้</dt><dd>{money(b.revPace.behind)}</dd></div><div><dt>ยอดขายเทียบจังหวะวันนี้</dt><dd>{pct(b.revPace.pctOfExpected)}</dd></div><div><dt>งบที่ควรใช้ถึงวันนี้</dt><dd>{money(b.pace.expectedSpend)}</dd></div><div><dt>ใช้เงินเหนือจังหวะวันนี้</dt><dd>{money(b.pace.vsPace)}</dd></div><div><dt>คาดใช้เกินงบสิ้นเดือน</dt><dd>{money(b.pace.forecastOver)}</dd></div><div><dt>เดือนผ่านไป</dt><dd>{pct(b.pace.expected)}</dd></div></dl>}</section>}
      </div>:<section className="aw-panel">ไม่มีแบรนด์ในขอบเขตที่เลือก</section>}
    </div>
  </main>;
}
